@echo off
setlocal enabledelayedexpansion

:: --- 1. АВТО-ЗАПУСК ОТ ИМЕНИ АДМИНИСТРАТОРА ---
>nul 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"
if '%errorlevel%' NEQ '0' (
    echo Requesting Admin rights...
    goto UACPrompt
) else ( goto gotAdmin )

:UACPrompt
    echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
    echo UAC.ShellExecute "%~s0", "", "", "runas", 1 >> "%temp%\getadmin.vbs"
    "%temp%\getadmin.vbs"
    exit /B

:gotAdmin
    if exist "%temp%\getadmin.vbs" ( del "%temp%\getadmin.vbs" )
    pushd "%CD%"
    CD /D "%~dp0"

:: --- 2. НАСТРОЙКИ ---
set "hosts_file=%SystemRoot%\System32\drivers\etc\hosts"
set "IP=85.137.95.246"

:: Список доменов для очистки и добавления
set "DOMAINS=elevenlabs.io chatgpt.com ab.chatgpt.com auth.openai.com auth0.openai.com platform.openai.com cdn.oaistatic.com files.oaiusercontent.com cdn.auth0.com tcr9i.chat.openai.com webrtc.chatgpt.com gemini.google.com aistudio.google.com generativelanguage.googleapis.com alkalimakersuite-pa.clients6.google.com copilot.microsoft.com sydney.bing.com edgeservices.bing.com claude.ai aitestkitchen.withgoogle.com aisandbox-pa.googleapis.com x.ai grok.com accounts.x.ai labs.google anthropic.com api.anthropic.com api.openai.com"

echo.
echo [1/3] Creating backup...
copy /y "%hosts_file%" "%hosts_file%.bak.%RANDOM%" >nul
echo       Backup saved.

echo.
echo [2/3] Updating entries with IP %IP%...
attrib -r "%hosts_file%" >nul 2>&1
set "PS_B64=JABoAG8AcwB0AHMAXwBwAGEAdABoACAAPQAgACQAZQBuAHYAOgBoAG8AcwB0AHMAXwBmAGkAbABlAAoAJABpAHAAIAA9ACAAJABlAG4AdgA6AEkAUAAKACQAZABvAG0AcwAgAD0AIAAkAGUAbgB2ADoARABPAE0AQQBJAE4AUwAuAFMAcABsAGkAdAAoACcAIAAnACkACgAkAHQAeAB0ACAAPQAgAGkAZgAgACgAVABlAHMAdAAtAFAAYQB0AGgAIAAkAGgAbwBzAHQAcwBfAHAAYQB0AGgAKQAgAHsAIABHAGUAdAAtAEMAbwBuAHQAZQBuAHQAIAAkAGgAbwBzAHQAcwBfAHAAYQB0AGgAIAB9ACAAZQBsAHMAZQAgAHsAIABAACgAKQAgAH0ACgAkAG8AdQB0ACAAPQAgAEAAKAApAAoAJABmAG8AdQBuAGQAIAA9ACAAQAB7AH0ACgBmAG8AcgBlAGEAYwBoACAAKAAkAGwAIABpAG4AIAAkAHQAeAB0ACkAIAB7AAoAIAAgACAAIAAkAHIAZQBwAGwAYQBjAGUAZAAgAD0AIAAkAGYAYQBsAHMAZQAKACAAIAAgACAAZgBvAHIAZQBhAGMAaAAgACgAJABkACAAaQBuACAAJABkAG8AbQBzACkAIAB7AAoAIAAgACAAIAAgACAAIAAgAGkAZgAgACgAJABsACAALQBtAGEAdABjAGgAIAAoACcAXgAoAD8AaQApAFwAcwAqAFsAXgAjAFwAcwBdACsAXABzACsALgAqAFwAYgAnACAAKwAgAFsAcgBlAGcAZQB4AF0AOgA6AEUAcwBjAGEAcABlACgAJABkACkAIAArACAAJwAoAD8AOgBcAGIAfAAkACkAJwApACkAIAB7AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAaQBmACAAKAAtAG4AbwB0ACAAJAByAGUAcABsAGEAYwBlAGQAKQAgAHsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAbAAgAD0AIAAkAGwAIAAtAHIAZQBwAGwAYQBjAGUAIAAnAF4AXABzACoAWwBeACMAXABzAF0AKwAnACwAIAAkAGkAcAAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJAByAGUAcABsAGEAYwBlAGQAIAA9ACAAJAB0AHIAdQBlAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAfQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAZgBvAHUAbgBkAFsAJABkAF0AIAA9ACAAJAB0AHIAdQBlAAoAIAAgACAAIAAgACAAIAAgAH0ACgAgACAAIAAgAH0ACgAgACAAIAAgACQAbwB1AHQAIAArAD0AIAAkAGwACgB9AAoAJABhAGQAZAAgAD0AIAAkAGYAYQBsAHMAZQAKAGYAbwByAGUAYQBjAGgAIAAoACQAZAAgAGkAbgAgACQAZABvAG0AcwApACAAewAKACAAIAAgACAAaQBmACAAKAAtAG4AbwB0ACAAJABmAG8AdQBuAGQAWwAkAGQAXQApACAAewAKACAAIAAgACAAIAAgACAAIABpAGYAIAAoAC0AbgBvAHQAIAAkAGEAZABkACkAIAB7AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABvAHUAdAAgACsAPQAgACcAJwAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAbwB1AHQAIAArAD0AIAAnACMAIAAtAC0ALQAgAEEASQAgAEgATwBTAFQAUwAgAEYASQBYACAAUwBUAEEAUgBUACAALQAtAC0AJwAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAYQBkAGQAIAA9ACAAJAB0AHIAdQBlAAoAIAAgACAAIAAgACAAIAAgAH0ACgAgACAAIAAgACAAIAAgACAAJABvAHUAdAAgACsAPQAgACIAJABpAHAAIAAkAGQAIgAKACAAIAAgACAAfQAKAH0ACgBpAGYAIAAoACQAYQBkAGQAKQAgAHsACgAgACAAIAAgACQAbwB1AHQAIAArAD0AIAAnACMAIAAtAC0ALQAgAEEASQAgAEgATwBTAFQAUwAgAEYASQBYACAARQBOAEQAIAAtAC0ALQAnAAoAfQAKACQAdQB0AGYAOABOAG8AQgBvAG0AIAA9ACAATgBlAHcALQBPAGIAagBlAGMAdAAgAFMAeQBzAHQAZQBtAC4AVABlAHgAdAAuAFUAVABGADgARQBuAGMAbwBkAGkAbgBnACAAJABmAGEAbABzAGUACgBbAEkATwAuAEYAaQBsAGUAXQA6ADoAVwByAGkAdABlAEEAbABsAEwAaQBuAGUAcwAoACQAaABvAHMAdABzAF8AcABhAHQAaAAsACAAWwBzAHQAcgBpAG4AZwBbAF0AXQAkAG8AdQB0ACwAIAAkAHUAdABmADgATgBvAEIAbwBtACkACgA="
powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand %PS_B64%

echo.
echo [3/3] Flushing DNS cache...
ipconfig /flushdns >nul

echo.
echo ==============================================
echo  SUCCESS! ALL HOSTS UPDATED.
echo ==============================================
pause
